### ISSUE TITLE
Ausführliche Logausgabe reduziert ausgegebene Informationen

### ISSUE THREAD

**Issue by j3nsch** [OPUS4/opus4-bibtex#28]
Sowohl im CLI als auch im Import-Formular (Administration > Dokumente > BibTeX-Import) gibt es die Möglichkeit, eine ausführliche Logausgabe zu erhalten. Das funktioniert nicht. Schaltet man das ein, sieht man selbst die einfachen Meldungen wie "S"=skipped oder "E"=error nicht mehr, die man ohne ausfürliche Logausgabe sieht.

Intern: https://tickets.zib.de/jira/browse/OPUSVIER-4569

**Comment by j3nsch** [comment]
Symfony Console unterstützt eine Verbosity-Option in drei Stufen. Das wird aber vom Import-Kommando nicht berücksichtigt. Die Option muss angepasst/entfernt werden bzw. die Unterstützung im Kommando umgesetzt werden. Durch die Standard-Optionen kann es zu Verwirrungen kommen.

Der BibTeX-Code scheint Verbosity zu berücksichtigen, zumindest in einer Stufe. Der Code muss noch mal überarbeitet werden, damit bei höheren Verbosity-Stufen, die Informationen nicht wieder geringer werden.

**Comment by j3nsch** [comment]
@sigwei, @stconradr Evtl. funktioniert das jetzt schon wieder, aber ich muss noch mal prüfen, ob alle Verbosity-Stufen korrekt interpretiert werden. Die Informationsmenge habe ich nicht erhöht.

**Comment by j3nsch** [comment]
Auf der Kommandozeile scheint es wie erwartet zu funktionieren, wobei die unterschiedlichen Verbosity-Level keinen Unterschied machen. In der Administration sehe ich keinen Unterschied zwischen Verbose an oder aus, zumindest nicht bei Thorsten's  BibTeX-Datei.

**Comment by sigwei** [comment]
In drei Fällen wird die Logausgabe weiterhin reduziert:

1. Dry und verbose, wenn die Dokumente importiert werden könnten
2. Error (E) und verbose
3. Error (E), verbose und  dry

Interessanterweise funktioniert das bei skip (S) und verbose, auch bei skip, verbose und dry.

**Comment by j3nsch** [comment]
Ich nehme an, da nicht weiter angegeben, es geht um Kommandozeile und Webseite. Außerdem wäre es nützlich zu dokumentieren was die Erwartung ist. Auf der Kommandozeile bekomme ich ohne Verbose, nur sehr wenige ausgaben und mit Verbose-Option, die Anzeige der Punkte für die verarbeiteten Dokumente. Ich glaube hier gibt es Missverständnisse zur Funktionalität.

Wenn ein Fehler bei der Umwandlung mit Pandoc stattfindet, dann kann der OPUS 4 PHP Code nicht viel machen, weil er gar nicht die Chance bekommt die Datensätze einzeln zu verarbeiten. In diesem Fall kann daher auch die Verbose-Funktion nichst ausrichten, weil der Fehler außerhalb stattfindet und mehr als die Fehlermeldung gibt es dann nicht.

**Comment by sigwei** [comment]
Ich habe sowohl auf Kommandozeile, als auch auf der Webseite noch einmal mit der aktuellen Version von Branch 4.7.1 getestet und passe meinen Kommentar von gestern wie folgt an:

Verbose auf der Kommandozeile bringt "."=erfolgreich, "S"=Skipped und "E"=Error, auf der Webseite nicht. Diese Zeichen sind aber hilfreich, wenn man die Datensätze identifizieren will, die nicht verarbeitet werden können.

Verbose gibt sowohl auf der Kommandozeile, als auch auf der Webseite bei erfolgreich importierten Datensätzen eine Meldung aus wie `Successful import of OPUS document 307` und bei skipped Datensätzen `Found existing OPUS document 307 with same hash value (md5:0c3e8aaa88d5dcb2576fa8b2274eb7cd)` .

Bei fehlerhaften Importen gibt Verbose auf der Kommandozeile lediglich "E" aus, also keine weiteren Hinweise, auf der Webseite sehe ich nichts davon.
