### ISSUE TITLE
Verknüpfung zu mehreren Sammlungen im CLI nicht möglich

### ISSUE THREAD

**Issue by sigwei** [OPUS4/opus4-bibtex#34]
Der BibTeX-Import hat eine Verknüpfung mit Sammlungen implementiert, wobei auch mehrere Sammlungen angegeben werden können. Im CLI funktioniert das nicht. Es wird nur die erste Collection ID berücksichtigt.

```
Usage:
  bibtex:import [options] [--] <fileName>
Options:
-c, --collection=COLLECTION  Collection IDs (comma-separated) that documents will be assigned to (multiple values allowed)
```

**Comment by j3nsch** [comment]
Es sind zwei Varianten möglich. Die Option kann mehrfach verwendet werden, `-c 123 -c 345`, oder sie kann einmal mit einer Komma-separierten Liste, `-c 123,345`, verwendet werden. Die für die Implementation verwendete Software (Symfony Console) unterstützt nur die erste Variante direkt. Bei der zweiten Variante gab es noch Probleme, weil es Missverständnisse bei der Verwendung der Symfony Console API gab. Das ist jetzt behoben.

Die mehrfache Verwendung der Option mit mehreren Komma-separierten Listen wird nicht unterstützt.
