### ISSUE TITLE
BibTex Pre-Defined Rule für Collections

### ISSUE THREAD

**Issue by vgerlach** [OPUS4/opus4-bibtex#45]
Bisher ist es nicht möglich über den BibTex-Import Collections anzugeben. Es wird gewünscht, dass durch die Angabe eines Arrays mit kommaseparierten IDs die Zuweisung zur Collection möglich ist.

Im BibTex-File würde dann ein Eintrag der Form
    
    collections = {17157, 17670, 17688, 16201, 17162}

erfolgen.

**Comment by j3nsch** [comment]
Das Parsing ist einfach. Im Metadaten-Array für das zu importierende Dokumente, werden dabei für das Feld Collection Einträge mit den IDs angelegt.

``` PHP
[
    'Collection => [
        ['Id' => 17157],
        ['Id' => 17670],
        ['Id' => 17688],
        ['Id' => 16201],
        ['Id' => 17162],
    ]
]
```     
Wenn dann `Collection::fromArray` für die Einträge aufgerufen wird, werden die existierenden Collections instanziert und beim Abspeichern mit dem Dokument verknüpft, zumindest theoretisch. 

Bei Tests mit dem Import in der Application tritt noch ein Fehler auf, der vermutlich nicht schwer zu beheben ist. Es ist aber schwierig das Problem zu debuggen und durch Tests abzudecken. Der BibTeX-Code ist leider immer noch etwas zu stark verzahnt, um gezielte Unit-Tests einfach zu machen. Das muss aufgelöst werden, was den Aufwand für dieses Ticket beträchtlich erhöht.

**Comment by j3nsch** [comment]
Ich konnte im Framework einen Test anlegen, der das Problem repliziert. Es ist eine kleine Änderung notwendig. Dann müssen neue Releases vom **framework** und von **opus4-bibtex** veröffentlicht werden. Die Lizenzen #46 sollten dabei auch gleich mit erledigt werden. Für die Lizenzen funktioniert alles genauso, es muss aber noch etwas mehr Code im Framework angefasst werden. Die `fromArray`-Funktionalität ist noch nicht vollständig für alle Modelle umgesetzt.

**Comment by j3nsch** [comment]
Das funktioniert jetzt. Die Umsetzung kann im Branch **bibtex-4.7.1.2** von Application getestet werden. Wenn es keine Probleme gibt, dann gibt es am 13.9.2022 den Release des neuen BibTeX-Packages und des Frameworks mit den notwendigen Anpassungen.

**Comment by j3nsch** [comment]
Es gibt im Augenblick noch keine besondere Fehlerbehandlung für ungültige IDs. Der Import schlägt fehl, wenn die IDs nicht stimmen.

**Comment by vgerlach** [comment]
Tests mit keiner, einer und mehreren IDs verliefen wie erwünscht.
