### ISSUE TITLE
BibTex-Import von Lizenzen mittels ID

### ISSUE THREAD

**Issue by vgerlach** [OPUS4/opus4-bibtex#46]
Es ist gewünscht, dass man beim BibTex-Import auch Lizenzen mittels ID angeben kann. Dies könnte als Array erfolgen, also als

    licences = {id1, id2}

Ggf. ist dafür eine neue Pre-Defined Rule notwendig.

**Comment by j3nsch** [comment]
Das ist zusammen mit #45 umgesetzt worden und wird nach Tests im Hosting veröffentlicht werden.

Diese Lösung ist für eine konkrete Instanz nutzbar, bei der die IDs der Lizenzen bekannt ist. Es wäre sinnvoll zu überlegen, wie man Lizenzen für Menschen lesbar und unabhängig von internen Datenbank IDs im BibTeX erfassen und automatisch auf die Lizenzen in einer OPUS-Instanz mappen kann. Das wäre langfristig die nützlichere Lösung.

**Comment by vgerlach** [comment]
Test mit keiner, einer und mehreren Lizenzen verliefen fehlerfrei. 
Für die Zukunft - wie auch angemerkt - wäre zumindest der Hinweis, dass das Dokument aufgrund einer fehlerhaften ID nicht importiert werden konnte, hilfreich.
