### ISSUE TITLE
Error during import - Call to undefined method Pandoc\Pandoc::runWith() 

### ISSUE THREAD

**Issue by vgerlach** [OPUS4/opus4-bibtex#63]
While trying to import a BibTex-File (OPUS V 4.8, php composer.phar update was done) we get the following:
Call to undefined method Pandoc\Pandoc::runWith() 

Stacktrace

        Pandoc\Exceptions\BadMethodCall: Call to undefined method Pandoc\Pandoc::runWith() in /home/opus/opus4-hm/vendor/ueberdosis/pandoc/src/Pandoc.php:284
Stack trace:
#0 /home/opus/opus4-hm/vendor/renanbr/bibtex-parser/src/Processor/LatexToUnicodeProcessor.php(67): Pandoc\Pandoc->__call('runWith', Array)
#1 /home/opus/opus4-hm/vendor/renanbr/bibtex-parser/src/Processor/LatexToUnicodeProcessor.php(37): RenanBr\BibTexParser\Processor\LatexToUnicodeProcessor->decode('MISC')
#2 [internal function]: RenanBr\BibTexParser\Processor\LatexToUnicodeProcessor->__invoke(Array)
#3 /home/opus/opus4-hm/vendor/renanbr/bibtex-parser/src/Listener.php(42): array_map(Object(RenanBr\BibTexParser\Processor\LatexToUnicodeProcessor), Array)
#4 /home/opus/opus4-hm/vendor/opus4-repo/opus4-bibtex/src/Import/Parser.php(110): RenanBr\BibTexParser\Listener->export()
#5 /home/opus/opus4-hm/vendor/opus4-repo/opus4-bibtex/src/Import/Console/Helper/BibtexImportHelper.php(142): Opus\Bibtex\Import\Parser->parse()
#6 /home/opus/opus4-hm/modules/admin/controllers/ImportController.php(83): Opus\Bibtex\Import\Console\Helper\BibtexImportHelper->doImport(Object(Opus\Bibtex\Import\Console\Helper\BibtexImportResult))
#7 /home/opus/opus4-hm/vendor/opus4/zf1-future/library/Zend/Controller/Action.php(516): Admin_ImportController->bibtexAction()
#8 /home/opus/opus4-hm/vendor/opus4/zf1-future/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('bibtexAction')
#9 /home/opus/opus4-hm/vendor/opus4/zf1-future/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /home/opus/opus4-hm/vendor/opus4/zf1-future/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#11 /home/opus/opus4-hm/vendor/opus4/zf1-future/library/Zend/Application.php(400): Zend_Application_Bootstrap_Bootstrap->run()
#12 /home/opus/opus4-hm/public/index.php(86): Zend_Application->run()
#13 {main}

Request

        Zend_Controller_Request_Http::__set_state(array(
   '_paramSources' => 
  array (
    0 => '_GET',
    1 => '_POST',
  ),
   '_requestUri' => '/opus4-hm/admin/import/bibtex',
   '_baseUrl' => '/opus4-hm',
   '_basePath' => NULL,
   '_pathInfo' => '/admin/import/bibtex',
   '_params' => 
  array (
    'module' => 'admin',
    'controller' => 'import',
    'action' => 'bibtex',
  ),
   '_rawBody' => NULL,
   '_aliases' => 
  array (
  ),
   '_dispatched' => true,
   '_module' => 'admin',
   '_moduleKey' => 'module',
   '_controller' => 'import',
   '_controllerKey' => 'controller',
   '_action' => 'bibtex',
   '_actionKey' => 'action',
))

**Comment by vgerlach** [comment]
System is running with PHP7

**Comment by vgerlach** [comment]
Instance https://opus4mig.kobv.de/opus4-demo is affected, too.

**Comment by j3nsch** [comment]
Das liegt an den PDF-Deckblättern. Die BibTeX-Funktionalität wurde mit `ryakad/pandoc-php` entwickelt, während für die Deckblätter `ueberdosis/pandoc` genommen wurde. Beide Pacakge definieren einen Klasse `Pandoc\Pandoc`, die eine mit einer `run` Funktion, die andere mit `runWith`. Ich vermute welches Package verwendet wird kann von System zu System verschieden sein. BibTeX und PDF scheinen in Application keine Tests zu haben, da dort alles durchläuft.

Ich werde im Augenblick den Code von beiden Paketen nicht anfassen, um sie auf das jeweils andere Paket umzustellen. Das soll sich der PDF-Entwickler anschauen.

**Comment by vgerlach** [comment]
Ok, ich habe jetzt für die aktualisierten Instanzen das Paket ueberdosis "rausgeschmissen", da sonst der BibTex-Import nicht mehr funktioniert. Ich hinterlege das mal in unserer internen Update-Doku. 
Danke für die Antwort, hat mir sehr geholfen.

**Comment by j3nsch** [comment]
Nicht erledigt.

**Comment by j3nsch** [comment]
In **opus4-pdf** wird die neuere Pandoc-Library verwendet. Im BibTeX Code ist das aber keine direkte Abhängigkeit, sondern etwas, dass vom BibTeX-Parser verwendet wird. Wir müssten also den gesamten Parser austauschen, um die Pandoc-Library loszuwerden. 

Das macht es schwierig. Gibt es einen alternativen Parser? Kann der PDF-Code mit der viel älteren Pandoc-Library funktionieren?

**Comment by extracts** [comment]
Siehe auch OPUS4/opus4-pdf#63
